# Generated by Django 4.2.5 on 2023-11-14 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('order_total', models.FloatField()),
                ('items', models.CharField(max_length=800)),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_line_two', models.CharField(blank=True, max_length=35, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=35, null=True)),
                ('shipping_zip', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customerinfo')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
            ],
        ),
    ]
