# Generated by Django 4.2.5 on 2023-10-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('order_total', models.FloatField()),
                ('items', models.CharField(max_length=800)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customerinfo')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
            ],
        ),
    ]
