# Generated by Django 4.2.5 on 2023-12-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
    ]
