# Generated by Django 4.2.5 on 2023-11-14 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('line_two', models.CharField(blank=True, max_length=35, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
    ]
