# Generated by Django 4.2.5 on 2023-10-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_storehasstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storehasstock',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='storehasstock',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storehasstock',
            name='store',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
            preserve_default=False,
        ),
    ]
