# Generated by Django 4.2.5 on 2023-10-06 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_rename_product_id_storehasstock_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='store',
            name='line_two',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='zip',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
    ]
