# Generated by Django 4.2.5 on 2023-11-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_remove_store_zip_code_store_line_two_store_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehasstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
        ),
    ]
