# Generated by Django 4.2.5 on 2023-11-14 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=75, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('line_two', models.CharField(blank=True, max_length=35, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=35, null=True)),
                ('zip', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('other_information', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin')], default='employee', max_length=15)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Accounts.userinfo')),
            ],
            bases=('Accounts.userinfo',),
        ),
    ]
