# Generated by Django 4.2.5 on 2023-10-06 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userinfo_city_userinfo_line_two_userinfo_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zip',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
