# Generated by Django 4.2.5 on 2023-10-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_remove_store_zip_code_store_line_two_store_zip'),
        ('Accounts', '0003_alter_userinfo_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
        ),
    ]
