# Generated by Django 4.2.5 on 2023-12-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_userinfo_id_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinfo',
            name='stock_notifications',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
