# Generated by Django 4.2.5 on 2023-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_userinfo_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin')], default='employee', max_length=15),
        ),
    ]
