# Generated by Django 4.2.5 on 2023-10-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_userinfo_account_type_admininfo_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='managerinfo',
            name='account_type',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account_type',
            field=models.CharField(default='employee', max_length=15),
        ),
    ]
