# Generated by Django 4.2.5 on 2023-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_total', models.FloatField()),
                ('items', models.CharField(max_length=800)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Accounts.customerinfo')),
                ('employee_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Accounts.employeeinfo')),
                ('manager_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Accounts.managerinfo')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
            ],
        ),
    ]
