# Generated by Django 4.2.5 on 2023-12-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_userinfo_id_alter_userinfo_user'),
        ('Purchases', '0002_remove_purchase_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='customer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Accounts.customerinfo'),
        ),
    ]
