# Generated by Django 4.2.5 on 2023-12-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_userinfo_id_alter_userinfo_user'),
        ('Purchases', '0003_purchase_first_name_purchase_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='admin_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='Accounts.admininfo'),
        ),
    ]
