# Generated by Django 4.2.5 on 2023-12-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_userinfo_id_alter_userinfo_user'),
        ('Stores', '0001_initial'),
        ('Purchases', '0004_purchase_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='Accounts.admininfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Accounts.customerinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Accounts.employeeinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Accounts.managerinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
        ),
    ]
