# Generated by Django 4.2.5 on 2023-12-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_managerinfo_stock_notifications'),
        ('Purchases', '0006_alter_purchase_admin_id_alter_purchase_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Accounts.customerinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
