# Generated by Django 4.2.5 on 2023-12-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
        ('Shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
        ),
    ]
