# Generated by Django 4.2.5 on 2023-12-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0002_alter_shipment_destination_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_freight_company',
            field=models.CharField(default='Fedex', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_tracking_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_tracking_history',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
