# Generated by Django 4.2.5 on 2023-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0003_shipment_shipment_freight_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
    ]
