# Generated by Django 4.2.5 on 2023-12-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0004_shipment_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipped_date',
            field=models.DateField(),
        ),
    ]
