# Generated by Django 4.2.5 on 2023-11-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_price', models.FloatField()),
                ('product_location', models.CharField(max_length=10)),
            ],
        ),
    ]
