# Generated by Django 4.2.5 on 2023-11-14 08:54

import Products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
        ('Products', '0001_initial'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
        ),
    ]
