# Generated by Django 4.2.5 on 2023-12-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_order_items'),
        ('Purchases', '0002_remove_purchase_items'),
        ('Products', '0005_purchaseitems_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseItems',
            new_name='ProductInOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='ProductInPurchase',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='purchase_info_object',
        ),
        migrations.RemoveField(
            model_name='productinpurchase',
            name='order_info_object',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='order_info_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinpurchase',
            name='purchase_info_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Purchases.purchase'),
            preserve_default=False,
        ),
    ]
