# Generated by Django 4.2.5 on 2023-12-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_rename_purchaseitems_productinorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='product_id',
            new_name='product',
        ),
    ]
