# Generated by Django 4.2.5 on 2023-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_rename_product_id_productincart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
