# Generated by Django 4.2.5 on 2023-12-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0005_alter_shipment_shipped_date'),
        ('Products', '0008_product_low_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipments.shipment')),
            ],
        ),
    ]
