# Generated by Django 5.0.3 on 2024-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_productinshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
